/*##########################################
#                                          #
#               ressources.h               #
#                                          #
#   Ce fichier regroupe tous les termes    #
#   utilisés pour mieux se repérer dans    #
#   le développement.                      #
#                                          #
##########################################*/

#ifndef RES
#define RES

#include <SDL/SDL.h>

#define TRUE 1
#define FALSE 0

#define W_HAUTEUR 500
#define W_LARGEUR 900
#define W_BPP 32

// Images
typedef enum enum_img enum_img;
enum {
     
     //images interface menu
     FOND, LOGO_MENU, BOUTON_JOUER, BOUTON_OPTIONS, BOUTON_QUITTER, BOUTON_AIDE, BOUTON_MENU,
     
     //images interface jeu
     BOUTON_CARTES, PION1, PION5, PION10, PION20, PION100, PION200, 
     GCARTE1, GCARTE2, GCARTE3, GCARTE4, GCARTE5, BOUTON_ANNULEMISE,
     SCARTEO1, SCARTEO2, SCARTEO3, SCARTEO4, SCARTEO5, SCARTEN1, SCARTEN2, SCARTEN3, 
     SCARTEN4, SCARTEN5, BANDE,
     
     //CARREAU
     DEUXCARREAU, TROISCARREAU, QUATRECARREAU, CINQCARREAU, SIXCARREAU, SEPTCARREAU, HUITCARREAU, NEUFCARREAU, DIXCARREAU, VALETCARREAU, DAMECARREAU, ROICARREAU, ASCARREAU,
     
     //COEUR
     DEUXCOEUR, TROISCOEUR, QUATRECOEUR, CINQCOEUR, SIXCOEUR, SEPTCOEUR, HUITCOEUR, NEUFCOEUR, DIXCOEUR, VALETCOEUR, DAMECOEUR, ROICOEUR, ASCOEUR,
    
     //PIQUE
     DEUXPIQUE, TROISPIQUE, QUATREPIQUE, CINQPIQUE, SIXPIQUE, SEPTPIQUE, HUITPIQUE, NEUFPIQUE, DIXPIQUE, VALETPIQUE, DAMEPIQUE, ROIPIQUE, ASPIQUE,
    
     //TREFLE
     DEUXTREFLE, TROISTREFLE, QUATRETREFLE, CINQTREFLE, SIXTREFLE, SEPTTREFLE, HUITTREFLE, NEUFTREFLE, DIXTREFLE, VALETTREFLE, DAMETREFLE, ROITREFLE, ASTREFLE,
     
     //images interface options
     BOUTON_MUSIQUESANS, BOUTON_MUSIQUEFAIBLE, BOUTON_MUSIQUEMOYEN, BOUTON_MUSIQUEFORT, BOUTON_SONSAVEC, 
     BOUTON_SONSSANS, BOUTON_MUSIQUE1, BOUTON_MUSIQUE2, BOUTON_MUSIQUESANSCOCHE, BOUTON_MUSIQUEFAIBLECOCHE, 
     BOUTON_MUSIQUEMOYENCOCHE, BOUTON_MUSIQUEFORTCOCHE, BOUTON_SONSAVECCOCHE, BOUTON_SONSSANSCOCHE, 
     BOUTON_MUSIQUE1COCHE, BOUTON_MUSIQUE2COCHE,
     
     //images interface aide
     BANDER1, BANDER2, BANDER3, BANDER4, COMBIPAIRE, COMBIDOUBLEPAIRE, COMBIBRELAN, 
     COMBICARRE, COMBICOULEUR, COMBIFULL, COMBIQUINTE, COMBIQUINTEFLUSH, COMBIQUINTEFLUSHROYALE
     
};

// pour la fonction get_state
typedef enum for_state for_state;
enum {
     
	W, H, X, Y
	
};

// Textes
typedef enum enum_text enum_text;
enum {
     
	TEXTE_SUPINFO, TEXTE_MISE, TEXTE_SELECT, TEXTE_SELECT2,
     
    PAIRE, DBPAIRE, BRELAN, QUINTE, FLUSH, FULL, CARRE, QFLUSH, QFLUSHR, 
    
    NOTHING, ARGENT, ARGENTSOMME, MISE, MISESOMME, 
    
    OPTIONSANS, OPTIONVOLUMEFAIBLE, OPTIONVOLUMEMOYEN, OPTIONVOLUMEFORT, OPTIONMUSIQUE, OPTIONSONS, 
    
    OPTIONSONSAVEC, OPTIONSONSSANS, OPTIONCHOIXMUSIQUE, OPTIONCHOIXMUSIQUE2, MUSIQUE1, MUSIQUE2, 
    
    PERDU, GAGNE, GAIN, GAINSOMME, 
    
    REGLE1, REGLE1BIS, REGLE1BIS2, REGLE1BIS3, REGLE2, REGLE2BIS, REGLE2BIS2, REGLE2BIS3, REGLE3, REGLE3BIS, 
    
    REGLE3BIS2, REGLE3BIS3, REGLE3BIS4, REGLE4, REGLE4BIS, REGLE4BIS2,
    
    TEXT_COMBIPAIRE, TEXT_COMBIDOUBLEPAIRE, TEXT_COMBIBRELAN, TEXT_COMBICARRE, TEXT_COMBICOULEUR, 
    
    TEXT_COMBIFULL, TEXT_COMBIQUINTE, TEXT_COMBIQUINTEFLUSH, TEXT_COMBIQUINTEFLUSHROYALE
    
};

//moteur audio
typedef enum enum_sound enum_sound;
enum {
     
    SON_PION, SON_CARTES, SON_BOUTON, SON_TAPIS, SON_APPLAUDISSEMENT, SON_WHAOU, SON_NOCOMBI, SON_PERDU
    
};

typedef enum enum_couleur enum_couleur;
enum {
     
	ROUGE, NOIRE
	
};

typedef enum enum_valeur enum_valeur;
enum {
     
	AS, ROI, DAME, VALET, UN, DEUX, TROIS, QUATRE, CINQ, SIX, SEPT, HUIT, NEUF, DIX
	
};

typedef enum enum_type enum_type;
enum {
     
	CARREAU, COEUR, PIQUE, TREFLE
	
};

typedef enum enum_action enum_action;
enum {
     
	PREMIERTIRAGE, SECONDTIRAGE, AUGMENTERMISE, CALCULDEGAIN, MISEAZERO, DEBUTPARTIE, ANNULEMISE, SAVE
	
};

// Couleurs, a completer au besoin
#define BLANC 255,255,255
#define NOIR 0,0,0
#define ROUGE 255,0,0
#define VERT 0,255,0

#endif
